# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/julio/Downloads/quanto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/julio/Downloads/quanto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/julio/Downloads/quanto/CMakeFiles /Users/julio/Downloads/quanto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/julio/Downloads/quanto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

Stats.o: Stats.cpp.o

.PHONY : Stats.o

# target to build an object file
Stats.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Stats.cpp.o
.PHONY : Stats.cpp.o

Stats.i: Stats.cpp.i

.PHONY : Stats.i

# target to preprocess a source file
Stats.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Stats.cpp.i
.PHONY : Stats.cpp.i

Stats.s: Stats.cpp.s

.PHONY : Stats.s

# target to generate assembly for a file
Stats.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Stats.cpp.s
.PHONY : Stats.cpp.s

Stock.o: Stock.cpp.o

.PHONY : Stock.o

# target to build an object file
Stock.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Stock.cpp.o
.PHONY : Stock.cpp.o

Stock.i: Stock.cpp.i

.PHONY : Stock.i

# target to preprocess a source file
Stock.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Stock.cpp.i
.PHONY : Stock.cpp.i

Stock.s: Stock.cpp.s

.PHONY : Stock.s

# target to generate assembly for a file
Stock.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Stock.cpp.s
.PHONY : Stock.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

run.o: run.cpp.o

.PHONY : run.o

# target to build an object file
run.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.cpp.o
.PHONY : run.cpp.o

run.i: run.cpp.i

.PHONY : run.i

# target to preprocess a source file
run.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.cpp.i
.PHONY : run.cpp.i

run.s: run.cpp.s

.PHONY : run.s

# target to generate assembly for a file
run.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.cpp.s
.PHONY : run.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... run"
	@echo "... Stats.o"
	@echo "... Stats.i"
	@echo "... Stats.s"
	@echo "... Stock.o"
	@echo "... Stock.i"
	@echo "... Stock.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

